#!/bin/bash

while true; do
    xrandr --output LVDS1 --mode 1920x1080 --output HDMI1 --mode 1280x800 --same-as LVDS1

    # TODO does this help any?
    #echo 'echo 3 > /proc/sys/vm/drop_caches' | sudo bash
    #sudo sync
    #sudo swapoff -a
    #sudo swapon -a

    sbt run
done
